# Generated by Django 5.1.4 on 2024-12-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documento_delete_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.persona'),
        ),
    ]
