# Generated by Django 5.1.4 on 2024-12-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_documento_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.persona'),
        ),
    ]
